// Generated by CoffeeScript 1.4.0
(function() {
  var _convertNumberToHex;

  _convertNumberToHex = function(number) {
    return '#' + _.str.lpad((+number).toString(16), 6, '0').toUpperCase();
  };

  this.Ctrl = function($scope) {
    $scope.style = {
      background: '#FFFFFF'
    };
    $scope.number = (1 << 24) - 1;
    return $scope.change = function() {
      return $scope.style.background = _convertNumberToHex($scope.number);
    };
  };

}).call(this);
