// Generated by CoffeeScript 1.4.0
(function() {
  var persister, route, scope;

  persister = new Persister('http://localhost:40643/api/', this.http, function(str) {
    return CryptoJS.SHA1(str).toString();
  });

  scope = {};

  $('.js-view').data('scope', scope);

  scope.persister = persister;

  route = function() {
    var page;
    if (!(location.hash.length > 3)) {
      location.hash = persister.isLoggedIn() ? '#!/game.html' : '#!/sign-in.html';
    }
    page = location.hash.substr(3);
    return $('.js-view').load('templates/' + page);
  };

  window.addEventListener('hashchange', route);

  route();

}).call(this);
