// Generated by CoffeeScript 1.4.0
(function() {
  var Person,
    __hasProp = {}.hasOwnProperty;

  this.Person = Person = (function() {

    function Person(firstName, lastName, age) {
      this.firstName = firstName;
      this.lastName = lastName;
      this.age = age;
    }

    Person.prototype.toString = function() {
      var key, value;
      return this.constructor.name.toUpperCase() + ": " + ((function() {
        var _results;
        _results = [];
        for (key in this) {
          if (!__hasProp.call(this, key)) continue;
          value = this[key];
          _results.push("" + key + ": " + value);
        }
        return _results;
      }).call(this)).join('; ');
    };

    return Person;

  })();

}).call(this);
