// Generated by CoffeeScript 1.4.0
(function() {
  var Class;

  this.Class = Class = (function() {

    function Class(name, formTeacher, capacity) {
      this.name = name;
      this.formTeacher = formTeacher;
      this.students = new Array(capacity);
    }

    Class.prototype.addStudent = function() {
      var student, _i, _len;
      for (_i = 0, _len = arguments.length; _i < _len; _i++) {
        student = arguments[_i];
        this.students.push(student);
      }
      return this;
    };

    return Class;

  })();

}).call(this);
