// Generated by CoffeeScript 1.4.0
(function() {
  var School;

  this.School = School = (function() {

    function School(name, town) {
      this.name = name;
      this.town = town;
      this.classes = [];
    }

    School.prototype.addClass = function() {
      var klass, _i, _len;
      for (_i = 0, _len = arguments.length; _i < _len; _i++) {
        klass = arguments[_i];
        this.classes.push(klass);
      }
      return this;
    };

    return School;

  })();

}).call(this);
